# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            TrustAI Workshop 2023
tagline:          'TrustAI Workshop 2023'
description:      ''
url:              'http://trustaideepindaba.github.io/'
baseurl:          ''

author:
  name:           'TrustAI team'

paginate:         5
# Custom vars


plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
