# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            GeoAI for a Sustainable Future in Africa Workshop 2024
tagline:          'GeoAI for a Sustainable Future in Africa Workshop 2024'
description:      ''
url:              'http://geoaiafrica.github.io'
baseurl:          ''

author:
  name:           'GeoAI Africa team'

paginate:         5
# Custom vars


plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
