# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
gems: [jekyll-paginate, jekyll-gist]
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Celia Cintas 
tagline:          'Celia Cintas Homepage'
description:      'Celia Cintas is a Research Scientist at  <a href="https://researcher.watson.ibm.com/researcher/view.php?person=ibm-Celia.Cintas" target="_blank">IBM Research Africa</a> - Nairobi, Kenya. She is a member of the AI Science team at the Kenya Lab.<br> Email: cintas[dot]celia[at]gmail[dot]com'
url:              http://celiacintas.github.io
baseurl:          /

author:
  name:           'Celia Cintas'
  url:            https://twitter.com/RTFMCelia

paginate:         5

# Custom vars
googlescholar: 
   url:           'https://scholar.google.com/citations?view_op=list_works&hl=en&user=7C8_pL4AAAAJ'


