# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            TrustML Workshop 2022
tagline:          'TrustML Workshop 2022'
description:      ''
url:              'http://trustmldeepindaba.github.io/'
baseurl:          ''

author:
  name:           'TrustML team'

paginate:         5
# Custom vars


plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
