# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Celia Cintas Homepage
tagline:          'Celia Cintas Homepage'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://celiacintas.github.io
baseurl:          /

author:
  name:           'Celia Cintas'
  url:            https://twitter.com/RTFMCelia

paginate:         5

# Custom vars
version:         The template is from https://github.com/poole/hyde

