# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Celia Cintas 
tagline:          'Celia Cintas Homepage'
description:      ''
url:              'http://celiacintas.github.io'
baseurl:          ''

author:
  name:           'Celia Cintas'
  url:            https://twitter.com/RTFMCelia

paginate:         5
# Custom vars
googlescholar: 
   url:           'https://scholar.google.com/citations?view_op=list_works&hl=en&user=7C8_pL4AAAAJ'


plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
